homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Planning
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

# view_event:
#   name: planning
#   components:
#     - calendar
#     - wunderlist

http:
#  base_url: https://automation.prettybaked.com
#  server_port: !secret planning_server_public_port
  
frontend:

config:

google: !include google.yaml
wunderlist: !include wunderlist.yaml
# TODO: Package tracking sensors

mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
# mqtt_remoteinstance: !include mqtt_remoteinstance.yaml
